apiVersion: v1
kind: Service
metadata:
  name: k8service
spec:
  selector:
    app: servicepod   # 👈 matches Pod label
  ports:
    - protocol: TCP
      port: 80         # Service port
      targetPort: 80   # Pod container port
  type: ClusterIP
