apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: project3-elk
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/*.log
      pos_file /var/log/fluentd.pos
      tag kube.logs
      format none
    </source>
    
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd2.pos
      tag kubernetes.*
      format none
     </source>    

    <match system.logs>
      @type elasticsearch
      host elasticsearch-service
      port 9200
      logstash_format true
      logstash_prefix system-logs
    </match>

    <match kubernetes.**>
      @type elasticsearch
      host elasticsearch-service
      port 9200
      scheme http
      logstash_format true
      logstash_prefix k8s-logs
    </match>
