apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: test-nginxapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: node:18
          ports:
            - containerPort: 3000
          command: ["node", "-e"]
          args:
            - |
              const http = require('http');
              const server = http.createServer((req, res) => {
                res.end('Backend is running');
              });
              server.listen(3000);
